version: '3.9'

services:
  db-catalogo:
    container_name: db-catalogo
    hostname: db-catalogo
    image: postgres:15.6
    ports:
      - '8001:5432'
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'pg_isready -U ${DB_USER:-pguser} -d ${DB_NAME:-catalogo}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME:-pguser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pgpwd}
      POSTGRES_DB: ${DB_NAME:-catalogo}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    restart: always
    networks:
      - rms

  api-catalogo:
    container_name: api-catalogo
    hostname: api-catalogo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    expose:
      - 3001
    env_file:
      - .env
    environment:
      DB_HOST: db-catalogo
      DB_PORT: 5432
      DB_USER: ${DB_USERNAME:-pguser}
      DB_PASSWORD: ${DB_PASSWORD:-pgpwd}
      DB_NAME: ${DB_NAME:-rms}
      DB_SSL: ${DB_SSL:-false}
    restart: always
    networks:
      - rms
    depends_on:
      - db-catalogo

networks:
  rms:
    name: rms_network
    driver: bridge
    external: true

volumes:
  postgres:
