apiVersion: v1
kind: Secret
metadata:
  name: rms-api-catalogo-secret
  namespace: rms
type: Opaque
data:
  # Dica: Você pode usar o https://www.base64encode.org/ para converter de/para Base64
  DB_HOST: cG9zdGdyZXM= # postgres
  DB_PORT: NTQzMg== # 5432
  DB_USERNAME: cGd1c2Vy
  DB_PASSWORD: cGdwd2Q=

  # ATENÇÃO: Evite fazer commit dos Secrets do Kubernetes em repositórios públicos
  # Para mais informações visite https://kubernetes.io/docs/concepts/security/secrets-good-practices/#avoid-sharing-secret-manifests
