apiVersion: apps/v1
kind: Deployment
metadata:
  name: rms-api-catalogo
  namespace: rms
  labels:
    app: rms-api-catalogo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rms-api-catalogo
  template:
    metadata:
      labels:
        app: rms-api-catalogo
    spec:
      serviceAccountName: aws-iam-serviceaccount # ServiceAccount com Role que permite acesso ao AWS Secrets Manager
      automountServiceAccountToken: false
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: aws-secrets
      containers:
        - name: rms-api-catalogo
          image: 900534935988.dkr.ecr.us-east-1.amazonaws.com/rms-api-catalogo:latest
          envFrom:
            - configMapRef:
                name: rms-api-catalogo-config
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-bff-secret
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-bff-secret
                  key: port
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-bff-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-bff-secret
                  key: password
          ports:
            - containerPort: 3001
          resources:
            # You must specify requests for CPU to autoscale
            # based on CPU utilization
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "0.5"
              memory: "1Gi"
              ephemeral-storage: "2Gi"